mavlink:
  connection_string: "/dev/ttyACM0"
  baud_rate: 115200
  stream_rate_hz: 50

ros:
  publish_rate_hz: 20
  
  topics:
    global_position: "/pixhawk/global_position"
    attitude: "/pixhawk/attitude"
    init_position: "/IBN/init_pos"