services:
  pixhawk_bridge:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: pixhawk_bridge:ibn
    container_name: pixhawk_bridge
    # volumes:
      # - ./src:/root/dev/src
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    restart: unless-stopped
    command: "ros2 launch ibn_mavlink pixhawk_bridge.launch.py"
    # command: "ros2 run ibn_mavlink pixhawk_bridge"
    # command: "ros2 run ibn_mavlink gps_injection"
    # command: "bash"
