mavlink:
  connection_string: "/dev/ttyACM0"
  baud_rate: 115200
  stream_rate_hz: 50

ros:
  publish_rate_hz: 20
  global_position_topic: "/pixhawk/global_position"
  attitude_topic: "/pixhawk/attitude"
  init_position_topic: "/IBN/init_pos"